apiVersion: v1
kind: PersistentVolume
metadata:
  name: public-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfsdata/app/deploy/public
    server: 192.168.10.178
