apiVersion: v1
kind: Service
metadata:
  name: priv-service
spec:
  type: NodePort
  selector:
    app: priv
  ports:
    - name: priv-web
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32113
    - name: priv1
      protocol: TCP
      targetPort: 30165
      port: 30165

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
   name: priv
spec:
  selector:
    matchLabels:
      app: priv
  template:
    metadata:
      labels:
        app: priv
    spec:
      containers:
      - image: mytomcat:v3.0
        imagePullPolicy: IfNotPresent
        name: priv
        #env:
        #- name: MYSQL_ROOT_PASSWORD
        #  value: password
        ports:
        - containerPort: 8080
          name: priv
        volumeMounts:
        - name: priv-storage
          mountPath: /opt/apache-tomcat-7.0.55/webapps/
        - name: priv-configmap
          mountPath: /opt/env/cityprivilige
      volumes:
      - name: priv-storage
        persistentVolumeClaim:
          claimName: priv-pvc
      - name: priv-configmap
        configMap:
          name: citypriv-configmap
