apiVersion: v1
kind: Service
metadata:
  name: console
spec:
  type: NodePort
  selector:
    app: console
    citycloud: console
  ports:
    - name: console-web
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32112

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: console
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
        citycloud: console
    spec:
      nodeSelector:
        cityconsole: cityconsole
      containers:
      - image: mytomcat:v3.0
        imagePullPolicy: IfNotPresent
        name: console
        ports:
        - containerPort: 8080
          name: console
        livenessProbe:
          exec:
            command:
              - cat
              - /etc/redhat-release
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /cityconsole
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
        volumeMounts:
        - name: console-storage
          mountPath: /opt/apache-tomcat-7.0.55/webapps/
        - name: console-configmap
          mountPath: /opt/env/cityconsole
        resources:
          limits:
            #cpu: 2048m
            memory: 1024Mi
            cpu: 4
            #memory: 6Gi
          requests:
            cpu: 1m
            memory: 512Mi
            #cpu: 4
            #memory: 6Gi
      volumes:
      - name: console-storage
        persistentVolumeClaim:
          claimName: console-pvc
      - name: console-configmap
        configMap:
          name: cityconsole-configmap
