apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  #ports:
  #- port: 3306
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 30306

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
   name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
